services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -m uvicorn chives_backend.main:app --host 0.0.0.0 --port 8000 --reload 